USE [test]
GO

INSERT INTO [dbo].[Model]([ModelName],[ModelType] ,[ModelImagePath],[ModelPrice])
     VALUES
           ('Klasa A', 'Hatchback', '/images/Klasa A.png', 127800),
		   ('EQS', 'Limuzyna', '/images/EQS.png', 333600),
		   ('Klasa C Kombi', 'Kombi', '/images/Klasa C Kombi.png', 201820),
		   ('Klasa E Kombi', 'Kombi', '/images/Klasa E Kombi.png', 233800),
		   ('EQA', 'SUV', '/images/EQA.png', 216100),
		   ('Klasa C Coupe', 'Coupe', '/images/Klasa C Coupe.png', 199400),
		   ('CLA Coupe', 'Coupe', '/images/CLA Coupe.png', 144400),
		   ('Klasa C Kabriolet', 'Kabriolet', '/images/Klasa C Kabriolet.png', 236500),
		   ('SL Roadster', 'Roadster', '/images/SL Roadster.png', 587400),
		   ('EQV', 'Van', '/images/EQV.png', 331116)
GO

INSERT INTO [dbo].[Engine]([EngineName],[EngineType],[EngineDisplacement],[EnginePower],[EnigneFuelConsumption],[EnginePowerConsumption],[EnginePrice])
     VALUES
           ('A 250 e', 'Hybrydowy', 1332, 160, 1.4, 14.8, 163200), 
           ('A 180', 'Benzynowy', 1332, 100, 5.5, NULL, 122800), 
           ('EQS 350', 'Elektryczny', NULL, 215, NULL, 17.1, 453300), 
           ('C 300 e', 'Hybrydowy', 1999, 245, 0.6, 19.8 , 232200), 
           ('C 200 d kombi', 'Diesel', 2148, 135, 4.7, NULL, 194200), 
           ('E 200', 'Benzynowy', 1991, 145, 7.4, NULL, 227800), 
           ('E 200 d', 'Diesel', 1597, 118, 5.2, NULL, 206800), 
           ('EQA 250', 'Elektryczny', NULL, 140, NULL, 17.6, 204500), 
           ('C 220 d coupe', 'Diesel', 1950, 135, 5.3, NULL, 204200), 
           ('C 180 coupe', 'Benzynowy', 1497, 115, 8.9, NULL, 186400), 
           ('CLA 250 e', 'Hybrydowy', 1332, 192, 0.9,6.9 , 180700), 
           ('CLA 250', 'Benzynowy', 1991, 165, 6.6, NULL, 170700), 
           ('C 220 d cabriolet', 'Diesel', 1950, 143, 5.6, NULL, 238100), 
           ('C 180 cabriolet', 'Benzynowy', 1497, 115, 9.1, NULL,222400 ), 
           ('SL 55 4MATIC+', 'Benzynowy', 3982, 350, 12.4, NULL, 812200), 
           ('SL 63 4MATIC+', 'Benzynowy', 3982, 430, 12.6, NULL, 959800), 
           ('EQV', 'Elektryczny', NULL, 150, NULL, 28.2, 286300)
GO

INSERT INTO [dbo].[ModelEngine] ([EngineId],[ModelId])
     VALUES
           ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'A 250 e'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'A 180'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'EQS 350'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQS')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 300 e'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kombi')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 200 d kombi'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kombi')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'E 200'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa E Kombi')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'E 200 d'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa E Kombi')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'EQA 250'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQA')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 220 d coupe'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Coupe')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 180 coupe'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Coupe')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'CLA 250 e'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'CLA 250'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 220 d cabriolet'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kabriolet')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'C 180 cabriolet'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kabriolet')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'SL 55 4MATIC+'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'SL Roadster')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'SL 63 4MATIC+'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'SL Roadster')),
		   ((SELECT EngineId FROM [dbo].[Engine] WHERE EngineName LIKE 'EQV'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQV'))
GO

INSERT INTO [dbo].[Equipment]([EquipmentName],[EquipmentPrice])
     VALUES
           ('Style',5398),
           ('Progressive',8098),
           ('AMG',14674),
           ('Electric Art',6636),
           ('AVANTGARDE',10420),
           ('EXCLUSIVE',0),
           ('AMG Plus',25866),
           ('Progressive 2',5914),
           ('Pregressive',7239),
           ('AMG 2',11926),
           ('Premium',32823),
           ('Premium Plus',51465)
GO

INSERT INTO [dbo].[ModelEquipment]([EquipmentId],[ModelId])
     VALUES
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive 2'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG 2'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa A')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Electric Art'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQS')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQS')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQS')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kombi')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kombi')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa E Kombi')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa E Kombi')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa E Kombi')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQA')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Electric Art'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQA')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'EQA')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG Plus'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive 2'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Pregressive'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG 2'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'CLA Coupe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kabriolet')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG Plus'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'Klasa C Kabriolet')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'SL Roadster')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium Plus'),(SELECT ModelId FROM [dbo].[Model] WHERE ModelName LIKE 'SL Roadster'))
GO

INSERT INTO [dbo].[Option]([OptionName],[OptionDescription],[OptionPrice])
     VALUES
        ('Pakiet wizualny i oswietleniowy',NULL,0),
		('Podwojny uchwyt na napoje',NULL,0),
		('Obrecze kol z metali lekkich, 16',NULL,0),
		('Reflektory w technologii LED, statyczne',NULL,0),
		('Obrecze kol z metali lekkich, 17',NULL,0),
		('Wielofunkcyjna kierownica wykonczona skora',NULL,0),
		('Komfortowe fotele przednie',NULL,0),
		('Elementy wykonczenia wnetrza - optyka karbonu',NULL,0),
		('Klimatyzacja automatyczna THERMOTRONIC',NULL,0),
		('Uklad hamulcowy dla linii AMG',NULL,0),
		('Sportowe fotele',NULL,0),
		('Obnizone zawieszenie',NULL,0),
		('Obrecze kol AMG ze stopow metali lekkich, 18',NULL,0),
		('Dywaniki AMG',NULL,0),
		('Przyciemniane szyby z funkcja termoizolacji',NULL,0),
		('Linia AMG - elementy zewnetrzne',NULL,0),
		('Linia AMG - elementy wewnetrzne',NULL,0),
		('Linia Electric Art. - elementy zewnetrzne',NULL,0),
		('Linia Style',NULL,0),
		('Linia Progressive',NULL,0),
		('Linia AMG',NULL,0),
		('Linia AVANTGARDE - elementy wewnetrzne',NULL,0),
		('Linia AVANTGARDE - elementy zewnetrzne',NULL,0),
		('Pakiet komfortowych siedzen',NULL,0),
		('Uklad hamulcowy o zwiekszonej wydajnosci',NULL,0),
		('Elementy wykonczenia wnetrza - blyszczace alumini',NULL,0),
		('Podswietlane listwy progowe',NULL,0),
		('Wykonczenie konsoli srodkowej - matowe drewno',NULL,0),
		('Linia EXCLUSIVE - elementy wewnetrzne',NULL,0),
		('Linia EXCLUSIVE - elementy zewnetrzne',NULL,0),
		('Elementy wykonczenia wnetrza - brazowe drewno',NULL,0),
		('Wykonczenie konsoli centralnej - brazowe drewno',NULL,0),
		('Elementy wykonczenia wnetrza - czarne drewno',NULL,0),
		('Tapicerka skorzana ARTICO/materialowa Fleron',NULL,0),
		('Aluminiowe relingi dachowe',NULL,0),
		('Elementy wykonczenia wnetrza - efekt spirali',NULL,0),
		('Reflektory LED High Performance',NULL,0),
		('Skladane oparcie tylnej kanapy',NULL,0),
		('Pakiet ochrony przed kradzieza URBAN GUARD Plus',NULL,0),
		('Wrazenia dzwiekowe AMG Real Performance',NULL,0),
		('Uslugi Remote Services Premium',NULL,0),
		('Head-up display',NULL,0),
		('Pakiet wyposazenia Premium',NULL,0),
		('Klimatyzowane fotele przednie',NULL,0)
GO

INSERT INTO [dbo].[EquipmentOption]([EquipmentId],[OptionId])
     VALUES 		
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Pakiet wizualny i oswietleniowy')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Podwojny uchwyt na napoje')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Obrecze kol z metali lekkich, 16')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Reflektory w technologii LED, statyczne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Style'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Wielofunkcyjna kierownica wykonczona skora')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Podwojny uchwyt na napoje')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Obrecze kol z metali lekkich, 17')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Komfortowe fotele przednie')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Elementy wykonczenia wnetrza - optyka karbonu')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Klimatyzacja automatyczna THERMOTRONIC')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Przyciemniane szyby z funkcja termoizolacji')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia AMG - elementy zewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Tapicerka skorzana ARTICO/materialowa Fleron')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Aluminiowe relingi dachowe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Sportowe fotele')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Obnizone zawieszenie')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Obrecze kol AMG ze stopow metali lekkich, 18')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Dywaniki AMG')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Electric Art'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Klimatyzacja automatyczna THERMOTRONIC')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Electric Art'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia Electric Art. - elementy zewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia AVANTGARDE - elementy wewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia AVANTGARDE - elementy zewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Pakiet komfortowych siedzen')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Elementy wykonczenia wnetrza - blyszczace alumini')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Podswietlane listwy progowe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AVANTGARDE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Wykonczenie konsoli srodkowej - matowe drewno')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Podswietlane listwy progowe')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia EXCLUSIVE - elementy wewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia EXCLUSIVE - elementy zewnetrzne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Elementy wykonczenia wnetrza - brazowe drewno')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'EXCLUSIVE'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Wykonczenie konsoli centralnej - brazowe drewno')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG Plus'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia AMG')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG Plus'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Uklad hamulcowy o zwiekszonej wydajnosci')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Obrecze kol AMG ze stopow metali lekkich, 18')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia Progressive')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Progressive 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Reflektory LED High Performance')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Pregressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Komfortowe fotele przednie')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Pregressive'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Elementy wykonczenia wnetrza - optyka karbonu')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Reflektory w technologii LED, statyczne')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Uklad hamulcowy dla linii AMG')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'AMG 2'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Linia AMG')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Pakiet ochrony przed kradzieza URBAN GUARD Plus')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Wrazenia dzwiekowe AMG Real Performance')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Uslugi Remote Services Premium')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium Plus'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Pakiet wyposazenia Premium')),
		((SELECT EquipmentId FROM [dbo].[Equipment] WHERE EquipmentName LIKE 'Premium Plus'),(SELECT OptionId FROM [dbo].[Option] WHERE OptionName LIKE 'Klimatyzowane fotele przednie'))
GO